version: '3.3'
services:
  iigomacs:
    build: .
    user: "${CURRENT_UID}"
    restart: always
    hostname: 'gomacs'
    environment:
      - SSH_AUTH_SOCK
    volumes:
      - '/tmp/iigomacs:/home/emacs/local'
      - '${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
