version: '3.3'
services:
  iigomacs:
    build: .
    user: "${CURRENT_UID}"
    restart: always
    hostname: 'gomacs'
    environment:
      - SSH_AUTH_SOCK
    volumes:
      - '/tmp/user:/user'
      - '${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}'
